services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - APP_PORT=3000
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:12.19
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rural-db
      - POSTGRES_SSL=false
    ports:
      - 5432:5432

networks:
  default:
    name: rural-network
